import { formatDateOnly } from "@/lib/utils/date";

export const ADMIN_LANGUAGE = "mk" as const;

export const adminCopy = {
  common: {
    appName: "Jajce Администратор",
    saveFallback: "Зачувано.",
    unknownError: "Се појави проблем.",
    resetForm: "Ресетирај форма",
    noValue: "—",
  },
  login: {
    eyebrow: "Админ",
    title: "Најава за админ",
    description: "Овој дел е наменет само за админ-контролната табла на jajce.mk.",
    email: "Е-пошта",
    password: "Лозинка",
    signIn: "Најави се",
    errors: {
      missing_credentials: "Внесете е-пошта и лозинка.",
      invalid_credentials: "Е-поштата или лозинката не се точни.",
      unknown: "Најавата не успеа.",
    },
  },
  layout: {
    title: "Контролна табла",
    dashboard: "Контролна табла",
    dailyLogs: "Дневни записи",
    costs: "Трошоци",
    contacts: "Контакти",
    orders: "Нарачки",
    notifications: "Известувања",
    margin: "Маржа",
    logout: "Одјави се",
  },
  dashboard: {
    eyebrow: "Фаза 5",
    title: "Контролна табла",
    description:
      "Админ KPI показатели што се пресметуваат серверски од залиха, дневни записи, нарачки, евидентирани трошоци и ознаки на контакти.",
    localDate: "Локален админ-датум",
    simple: "Основен",
    expanded: "Проширен",
    availableEggs: "Достапни јајца",
    availableEggsDetail: "Продажна залиха од инвентарската евиденција.",
    todayTotalYield: "Денешен вкупен принос",
    todayTotalYieldDetail: "Вкупен принос од денешниот дневен запис.",
    todayCollectedForSale: "Денес собрани за продажба",
    todayCollectedForSaleDetail: "Денешно количество за продажба од дневниот запис.",
    yesterdayCollectedForSale: "Вчера собрани за продажба",
    yesterdayCollectedForSaleDetail: "Вчерашно количество за продажба од дневниот запис.",
    latestChickenCount: "Последен број на кокошки",
    latestLog: "Последен запис",
    noDailyLogsYet: "Сè уште нема дневни записи.",
    todaySoldEggs: "Денес продадени јајца",
    todaySoldEggsDetail: "Количина од завршени нарачки признаена денес.",
    todayRevenue: "Денешен приход",
    todayRevenueDetail: "Приход од завршени нарачки признаен денес.",
    todayTotalCost: "Денешен вкупен трошок",
    todayTotalCostDetail: "Денешни директни и распределени евидентирани трошоци.",
    todayGrossMargin: "Денешна бруто маржа",
    todayGrossMarginDetail: "Денешен приход минус вкупен трошок.",
    subscriberCount: "Број на претплатници",
    subscriberCountDetail: "Контакти означени како претплатници.",
    waitingListCount: "Број на листа на чекање",
    waitingListCountDetail: "Контакти означени на листа на чекање.",
    activeCustomerCount: "Број на активни купувачи",
    activeCustomerCountDetail: "Контакти означени како активни купувачи.",
    homepageEyebrow: "Почетна страница",
    homepageTitle: "Видливост на јавна белешка",
    homepageDescription:
      "Јавната белешка од денешниот дневен запис се прикажува на почетната страница само кога оваа поставка е вклучена. Точната залиха останува видлива само за админ.",
    homepageSettingSaved: "Поставката за почетната страница е зачувана.",
    homepageSettingValidationError:
      "Проверете ја поставката за почетната страница и обидете се повторно.",
    homepageSettingUnknownError:
      "Поставката за почетната страница не можеше да се зачува.",
    homepageCheckbox:
      "Прикажи ја денешната јавна белешка на почетната страница кога постои во дневниот запис.",
    saveHomepageSetting: "Зачувај поставка за почетната страница",
    totalYieldPerChicken: "Вкупен принос по кокошка",
    totalYieldPerChickenDetail:
      "Нема вредност кога денешниот број на кокошки недостасува или е нула.",
    saleYieldPerChicken: "Принос за продажба по кокошка",
    saleYieldPerChickenDetail:
      "Денешни собрани јајца за продажба поделени со бројот на кокошки.",
    todayDirectCost: "Денешен директен трошок",
    todayDirectCostDetail: "Денешни евидентирани трошоци означени како директни.",
    todayAllocatedCost: "Денешен распределен трошок",
    todayAllocatedCostDetail:
      "Денешни евидентирани трошоци означени како распределени.",
    grossMargin7d: "Бруто маржа за 7 дена",
    grossMargin7dDetail: "Подвижна бруто маржа за последните 7 локални датуми.",
    grossMargin30d: "Бруто маржа за 30 дена",
    grossMargin30dDetail:
      "Подвижна бруто маржа за последните 30 локални датуми.",
    todayEyebrow: "Денес",
    costByCategoryTitle: "Трошоци по категорија",
    costByCategoryDescription: "Денешни евидентирани трошоци групирани по категорија.",
    noBookedCostsToday: "Нема евидентирани трошоци за денес.",
    category: "Категорија",
    totalAmount: "Вкупен износ",
  },
  dailyLogs: {
    eyebrow: "Дневни записи",
    createTitle: "Креирај дневен запис",
    editTitle: "Измени дневен запис",
    description:
      "Вкупниот принос секогаш се пресметува серверски од четирите полиња за дневен исход. Измените и бришењата се блокирани ако намалувањето на собраната количина би ја направило продажната залиха неконзистентна по резервации или завршени продажби.",
    errors: {
      validation: "Проверете ги полињата на дневниот запис и обидете се повторно.",
      duplicate_date: "Веќе постои дневен запис за тој датум.",
      not_found: "Избраниот дневен запис не беше пронајден.",
      inventory_conflict:
        "Оваа промена би отстранила собрана залиха што веќе е резервирана или продадена. Прво прилагодете ги поврзаните нарачки.",
      unknown: "Дневниот запис не можеше да се зачува.",
    },
    success: {
      saved: "Дневниот запис е зачуван.",
      deleted: "Дневниот запис е избришан.",
    },
    date: "Датум",
    chickenCount: "Број на кокошки",
    publicNote: "Јавна белешка",
    internalNotes: "Внатрешни белешки",
    update: "Ажурирај дневен запис",
    create: "Креирај дневен запис",
    recordsEyebrow: "Записи",
    recordsTitle: "Зачувани дневни записи",
    recordsDescription:
      "Бришењето на дневен запис го отстранува и неговиот евидентен ред за собрана залиха, па небезбедните бришења се блокираат штом таа залиха е резервирана или продадена.",
    empty: "Сè уште нема дневни записи.",
    totalYield: "Вкупен принос",
    collected: "Собрани",
    actions: "Акции",
    edit: "Измени",
    delete: "Избриши запис",
    eggFields: {
      collectedForSale: "Собрани јајца за продажба",
      usedOtherPurpose: "Јајца искористени за друга намена",
      broken: "Скршени јајца",
      unusableOther: "Неупотребливи јајца - друго",
      autoCalculatedTotalYield: "Автоматски пресметан вкупен принос",
    },
  },
  costs: {
    eyebrow: "Трошоци",
    bookTitle: "Евидентирај трошок",
    editTitle: "Измени трошок",
    acceptTitle: "Измени и прифати повторлив трошок",
    description:
      "Рачните трошоци се евидентираат овде, а шаблоните за повторливи трошоци се креираат од истиот тек кога е потребно. `total_amount` останува сметководствен извор на вистина при зачувување, а предлозите за повторливи трошоци и понатаму стануваат посебни евидентирани трошоци од шаблон кога се прифатени.",
    errors: {
      validation: "Проверете ги полињата за трошокот и обидете се повторно.",
      not_found: "Избраниот трошок не беше пронајден.",
      suggestion_unavailable:
        "Тој предлог за повторлив трошок не е достапен за избраниот датум.",
      duplicate_template_date:
        "Тој шаблон веќе е прифатен во евидентиран трошок за избраниот датум.",
      template_origin_locked:
        "Евидентирани трошоци од шаблон може да се создаваат само преку прифаќање предлог и не може да се уредуваат овде.",
      template_validation:
        "Проверете ги полињата за шаблонот за повторлив трошок и обидете се повторно.",
      template_not_found: "Избраниот шаблон за повторлив трошок не беше пронајден.",
      template_in_use:
        "Овој шаблон за повторлив трошок не може да се избрише бидејќи веќе е поврзан со евидентирани трошоци.",
      unknown: "Трошокот не можеше да се зачува.",
    },
    success: {
      saved: "Трошокот е зачуван.",
      saved_with_recurring:
        "Трошокот е зачуван и шаблонот за повторлив трошок е креиран.",
      deleted: "Трошокот е избришан.",
      accepted: "Предлогот за повторлив трошок е прифатен во евидентирани трошоци.",
      skipped: "Предлогот за повторлив трошок е прескокнат само за таа појава.",
      template_updated: "Шаблонот за повторлив трошок е ажуриран.",
      template_deleted: "Шаблонот за повторлив трошок е избришан.",
    },
    suggestionNoLongerPending:
      "Тој предлог за повторлив трошок повеќе не е во чекање за избраниот датум.",
    unknownTemplate: "Непознат шаблон",
    templateOriginLockedPrefix: "Овој евидентиран трошок доаѓа од шаблонот",
    templateOriginLockedSuffix:
      "Изменете го овој вид трошок преку промена на шаблонот и прифаќање нов предлог наместо тука.",
    acceptingSuggestionNote:
      "Ја уредувате само оваа појава пред прифаќање. Зачувувањето овде креира евидентиран трошок од шаблон само за избраниот датум и не ги менува стандардните вредности на шаблонот.",
    update: "Ажурирај трошок",
    saveEditedAcceptance: "Зачувај изменето прифаќање",
    create: "Креирај трошок",
    suggestionsEyebrow: "Предлози",
    suggestionsTitle: "Повторливи предлози",
    suggestionsDescription:
      "Активните шаблони за повторливи трошоци се прикажуваат овде за избраниот датум. Можете да ги прифатите како што се, да измените една појава пред прифаќање или да ја прескокнете само таа појава без да го исклучите шаблонот.",
    suggestionDate: "Датум за предлози",
    loadSuggestions: "Вчитај предлози",
    noSuggestionsMatchPrefix: "Нема повторливи предлози за",
    recurringPreviewEyebrow: "Повторлив преглед",
    recurringPreviewTitle: "Преглед на идни повторливи трошоци",
    recurringPreviewDescription:
      "Преглед само за читање на повторливи појави што чекаат, врз основа на тековните активни шаблони. Намерно останува компактен и не прераснува во интерфејс за распоред.",
    referenceDate: "Референтен датум",
    next7Days: "Следни 7 дена",
    next30Days: "Следни 30 дена",
    recurringTemplatesEyebrow: "Повторливи шаблони",
    recurringTemplatesTitle: "Животен циклус на шаблон",
    recurringTemplatesDescription:
      "Секојдневното управување со повторливи трошоци сега е овде. Користете активно / неактивно како главна контрола на животниот циклус, а одржувачката рута само за повремени детални измени.",
    openMaintenanceView: "Отвори одржување",
    noRecurringTemplatesYet: "Сè уште нема шаблони за повторливи трошоци.",
    template: "Шаблон",
    defaultTotal: "Стандарден вкупен износ",
    schedule: "Распоред",
    bookedCosts: "Евидентирани трошоци",
    status: "Статус",
    active: "Активен",
    inactive: "Неактивен",
    markInactive: "Означи како неактивен",
    markActive: "Означи како активен",
    maintenanceEdit: "Измени во одржување",
    deleteUnused: "Избриши некористен",
    deleteDisabledAfterBooking: "Бришењето е исклучено по евидентирање",
    bookedCostsEyebrow: "Евидентирани трошоци",
    bookedCostsTitle: "Зачувани трошоци",
    noBookedCostsYet: "Сè уште нема евидентирани трошоци.",
    date: "Датум",
    category: "Категорија",
    type: "Тип",
    total: "Вкупно",
    source: "Извор",
    actions: "Акции",
    edit: "Измени",
    deleteBookedCost: "Избриши евидентиран трошок",
    accepted: "Прифатено",
    skipped: "Прескокнато",
    accept: "Прифати",
    editAndAccept: "Измени и прифати",
    skip: "Прескокни",
    pendingOccurrenceCountSingular: "појава во чекање",
    pendingOccurrenceCountPlural: "појави во чекање",
    scheduledTotal: "Планиран вкупен износ",
    noPendingRecurringCosts: "Нема повторливи трошоци во чекање во овој период.",
    form: {
      date: "Датум",
      totalAmount: "Вкупен износ",
      category: "Категорија",
      costType: "Тип на трошок",
      quantity: "Количина",
      unit: "Единица",
      unitPrice: "Цена по единица",
      saveAsRecurring: "Зачувај како шаблон за повторлив трошок",
      recurringHelp:
        "Ова го креира евидентираниот трошок сега и зачувува посебен повторлив шаблон за идни предлози.",
      templateName: "Име на шаблон",
      frequency: "Фреквенција",
      templateIsActive: "Шаблонот е активен",
      startDate: "Почетен датум",
      endDate: "Краен датум",
      note: "Белешка",
    },
  },
  costTemplates: {
    eyebrow: "Одржување",
    createTitle: "Креирај повторлив шаблон",
    editTitle: "Измени повторлив шаблон",
    backToCosts: "Назад кон трошоци",
    description:
      "Ова е споредна рута за одржување. Главниот тек за повторливи трошоци сега е на страницата за трошоци, каде што евидентираните трошоци и повторливите шаблони се управуваат заедно. Користете го овој екран само за повремени детални измени или рачно расчистување.",
    errors: {
      validation:
        "Проверете ги полињата за шаблонот за трошок и обидете се повторно.",
      not_found: "Избраниот шаблон за трошок не беше пронајден.",
      in_use:
        "Овој шаблон за трошок не може да се избрише бидејќи веќе е поврзан со евидентирани трошоци.",
      unknown: "Шаблонот за трошок не можеше да се зачува.",
    },
    success: {
      saved: "Шаблонот за трошок е зачуван.",
      deleted: "Шаблонот за трошок е избришан.",
    },
    name: "Име",
    category: "Категорија",
    costType: "Тип на трошок",
    frequency: "Фреквенција",
    defaultQuantity: "Стандардна количина",
    defaultUnit: "Стандардна единица",
    defaultUnitPrice: "Стандардна цена по единица",
    defaultTotalAmount: "Стандарден вкупен износ",
    startDate: "Почетен датум",
    endDate: "Краен датум",
    templateIsActive: "Шаблонот е активен",
    note: "Белешка",
    update: "Ажурирај шаблон",
    create: "Креирај шаблон",
    templatesEyebrow: "Шаблони",
    templatesTitle: "Зачувани шаблони за трошоци",
    empty: "Сè уште нема шаблони за трошоци.",
    type: "Тип",
    defaultTotal: "Стандарден вкупен износ",
    schedule: "Распоред",
    bookedCosts: "Евидентирани трошоци",
    status: "Статус",
    actions: "Акции",
    edit: "Измени",
    deleteDisabledAfterBooking: "Бришењето е исклучено по евидентирање",
    deleteUnusedTemplate: "Избриши некористен шаблон",
  },
  contacts: {
    eyebrow: "Фаза 4",
    createTitle: "Креирај контакт",
    editTitle: "Измени контакт",
    description:
      "Контактите можат истовремено да имаат повеќе ознаки за улога, додека стадиумот на купувач останува посебно поле за животен циклус. Бришењето е блокирано кога контактот веќе е поврзан со нарачки или зачувана историја на известувања.",
    errors: {
      validation: "Проверете ги полињата за контакт и обидете се повторно.",
      not_found: "Избраниот контакт не беше пронајден.",
      in_use:
        "Овој контакт не може да се избрише бидејќи сè уште е поврзан со нарачки или историја на известувања.",
      unknown: "Контактот не можеше да се зачува.",
    },
    success: {
      saved: "Контактот е зачуван.",
      deleted: "Контактот е избришан.",
    },
    fullName: "Име и презиме",
    email: "Е-пошта",
    phone: "Телефон",
    subscriber: "Претплатник",
    waitingList: "Листа на чекање",
    activeCustomer: "Активен купувач",
    emailOptIn: "Согласност за е-пошта",
    phoneOptIn: "Согласност за телефон",
    preferredChannel: "Претпочитан канал",
    customerStage: "Стадиум на купувач",
    preferredQuantity: "Претпочитана количина",
    preferenceUnit: "Единица на преференција",
    notificationFrequency: "Фреквенција на известување",
    joinedWaitingListAt: "Додаден на листа на чекање на",
    becameCustomerAt: "Станал купувач на",
    source: "Извор",
    notes: "Белешки",
    update: "Ажурирај контакт",
    create: "Креирај контакт",
    recordsEyebrow: "Записи",
    recordsTitle: "Зачувани контакти",
    empty: "Сè уште нема контакти.",
    name: "Име",
    stage: "Стадиум",
    flags: "Ознаки",
    actions: "Акции",
    edit: "Измени",
    delete: "Избриши контакт",
    none: "Нема",
  },
  orders: {
    eyebrow: "Фаза 4",
    createTitle: "Креирај нарачка",
    editReservedTitle: "Измени резервирана нарачка",
    correctCompletedTitle: "Коригирај завршена нарачка",
    description:
      "Вкупната цена секогаш се пресметува во бекендот од количината и избраната цена по единица. Корекциите на завршени нарачки користат посебна сервисна патека, а вообичаените измени на резервирани нарачки остануваат блокирани кога поврзаната состојба на залиха повеќе не е безбедна или конзистентна.",
    errors: {
      validation: "Проверете ги полињата за нарачката и обидете се повторно.",
      not_found: "Избраната нарачка не беше пронајдена.",
      contact_not_found: "Избраниот контакт не беше пронајден.",
      insufficient_inventory:
        "Оваа операција би ја намалила продажната залиха под нула.",
      transition_not_allowed:
        "Таа промена на нарачката не е дозволена во вообичаениот тек за оваа состојба на нарачката.",
      completed_correction_required:
        "Завршените нарачки мора да се менуваат преку посебниот тек за корекција.",
      invalid_inventory_state:
        "Оваа нарачка има невалидна состојба на залиха и не може да се менува додека рачно не се провери.",
      unknown: "Нарачката не можеше да се зачува.",
    },
    success: {
      saved: "Нарачката е зачувана.",
      corrected: "Завршената нарачка е коригирана.",
    },
    createContactFirst: "Прво креирајте контакт, па потоа додајте нарачки.",
    contact: "Контакт",
    status: "Статус",
    completed: "Завршена",
    completedCorrectionWarning:
      "Оваа корекција го задржува оригиналниот инвентарски режим што ја намалува залихата и ќе биде блокирана ако поврзаната состојба на залиха е неконзистентна или ако корекцијата би предизвикала препродажба.",
    quantity: "Количина",
    unitPrice: "Цена по единица",
    backendComputedTotalPrice: "Вкупна цена пресметана во бекенд",
    fulfilledAt: "Реализирано на",
    note: "Белешка",
    applyCompletedCorrection: "Примени безбедна корекција на завршена нарачка",
    normalEditWarning:
      "Вообичаеното уредување е достапно само додека оваа нарачка е чиста резервација. Ако веќе преминала во неконзистентна состојба на залиха, ажурирањето ќе биде блокирано за рачна проверка.",
    orderDate: "Датум на нарачка",
    targetFulfillmentDate: "Целен датум на реализација",
    selectContact: "Изберете контакт",
    priceSource: "Извор на цена",
    manualUnitPrice: "Рачна цена по единица",
    calculatedOnSave: "Се пресметува при зачувување",
    update: "Ажурирај нарачка",
    create: "Креирај нарачка",
    recordsEyebrow: "Записи",
    recordsTitle: "Зачувани нарачки",
    empty: "Сè уште нема нарачки.",
    date: "Датум",
    totalPrice: "Вкупна цена",
    fulfilled: "Реализирано",
    actions: "Акции",
    edit: "Измени",
    correct: "Коригирај",
    lockedAfterStockRelease: "Заклучено по ослободување на залихата",
  },
  notifications: {
    eyebrow: "Фаза 7",
    createTitle: "Креирај нацрт-известување",
    editTitle: "Измени нацрт-известување",
    description:
      "Испраќањето преку е-пошта е активно во MVP. Viber и WhatsApp остануваат само подготвени во шемата во оваа фаза. Нацртите стануваат само за читање кога редовите за приматели ќе се зачуваат, за да остане конзистентна снимката за испраќање.",
    success: {
      saved: "Нацртот е зачуван.",
      sent: "Кампањата е успешно испратена. Снимката од приматели сега е заклучена во историјата.",
      failed:
        "Испраќањето заврши со едно или повеќе неуспешни доставувања. Проверете ги зачуваните броеви на приматели подолу.",
    },
    errors: {
      validation:
        "Проверете ги полињата за известувањето и обидете се повторно.",
      not_found: "Избраната кампања не беше пронајдена.",
      read_only: "Само нацрт-кампањи може да се уредуваат или испраќаат во Фаза 7.",
      unsupported_channel: "Во Фаза 7 е поддржано само испраќање преку е-пошта.",
      no_eligible_recipients:
        "Нема преостанати подобни приматели за е-пошта за оваа публика.",
      unknown: "Известувањето не можеше да се зачува или испрати.",
    },
    recoverableDraftWarning:
      "Овој нацрт веќе има зачувани редови за приматели, па е достапен само за испраќање додека не заврши финализацијата. Уредувањето е блокирано од безбедносни причини бидејќи снимката на приматели е веќе заклучена.",
    readOnlyRequestedWarning:
      "Испратените и неуспешните кампањи се само за читање. Празната форма подолу служи за креирање нов нацрт, а не за уредување на оваа кампања.",
    title: "Наслов",
    channel: "Канал",
    audience: "Публика",
    senderLabel: "Ознака на испраќач",
    subject: "Наслов на порака",
    body: "Содржина",
    selectedContactsTitle: "Избрани контакти",
    selectedContactsDescription:
      "Овие зачувани избори се користат само кога публиката е поставена на избрани контакти.",
    savedContactsSuffix: "зачувани контакти",
    noContactsYet:
      "Сè уште нема контакти. Додајте контакти прво за да користите кампањи со избрани контакти.",
    noEmail: "Нема е-пошта",
    noPhone: "Нема телефон",
    saveDraft: "Зачувај нацрт",
    createDraft: "Креирај нацрт",
    sendDraftTitle: "Испрати го овој нацрт",
    recoverableDraftDescription:
      "Овој нацрт веќе има зачувана снимка од приматели. Продолжувањето со испраќање ќе продолжи само со тие зачувани приматели.",
    sendDraftDescription:
      "Публиката повторно се пресметува при испраќање според тековните податоци за контакти. Подобни се само контакти со валидна е-пошта и експлицитна согласност за е-пошта.",
    resumeSending: "Продолжи со испраќање на зачуваната снимка",
    sendDraft: "Испрати нацрт",
    emailOnlyDraftWarning:
      "Овој нацрт може да се зачува, но во Фаза 7 е поддржано само испраќање преку е-пошта.",
    historyEyebrow: "Историја",
    historyTitle: "Кампањи",
    empty: "Сè уште нема кампањи за известувања.",
    recipients: "Приматели",
    updated: "Ажурирано",
    total: "Вкупно",
    sent: "Испратени",
    failed: "Неуспешни",
    sentOn: "Испратено",
    edit: "Измени",
    resume: "Продолжи",
    send: "Испрати",
  },
  margin: {
    eyebrow: "Фаза 3",
    title: "Маржинални увиди",
    description:
      "Пресметките за маржа се извршуваат во бекенд сервисите од евидентирани трошоци, приход од завршени нарачки и дневни производствени податоци.",
    date: "Датум",
    loadDate: "Вчитај датум",
    dailyRevenue: "Дневен приход",
    dailyRevenueDetail: "Завршени нарачки признаени на избраниот датум.",
    dailyDirectCost: "Дневен директен трошок",
    dailyDirectCostDetail: "Евидентирани трошоци означени како директни.",
    dailyAllocatedCost: "Дневен распределен трошок",
    dailyAllocatedCostDetail: "Евидентирани трошоци означени како распределени.",
    dailyTotalCost: "Дневен вкупен трошок",
    dailyTotalCostDetail: "Директни плус распределени евидентирани трошоци.",
    dailyGrossMargin: "Дневна бруто маржа",
    dailyGrossMarginDetail: "Приход минус вкупен трошок.",
    dailyDirectMargin: "Дневна директна маржа",
    dailyDirectMarginDetail: "Приход минус директен трошок.",
    costPerCollectedEgg: "Трошок по собрано јајце",
    costPerCollectedEggDetail:
      "Нема вредност кога нема собрани јајца за продажба.",
    marginPerSoldEgg: "Маржа по продадено јајце",
    marginPerSoldEggDetail: "Нема вредност кога нема продадени јајца.",
    summary7d: "Преглед за 7 дена",
    summary30d: "Преглед за 30 дена",
    rollingWindow: "Подвижен период",
    eggsTotalYield: "Вкупен принос на јајца",
    eggsCollectedForSale: "Собрани јајца за продажба",
    eggsSold: "Продадени јајца",
    revenue: "Приход",
    directCost: "Директен трошок",
    allocatedCost: "Распределен трошок",
    totalCost: "Вкупен трошок",
    grossMargin: "Бруто маржа",
  },
} as const;

const ADMIN_VALUE_LABELS: Record<string, string> = {
  email: "Е-пошта",
  viber: "Viber",
  whatsapp: "WhatsApp",
  all: "Сите",
  week: "Недела",
  month: "Месец",
  instant: "Веднаш",
  weekly: "Неделно",
  manual_only: "Само рачно",
  lead: "Потенцијален",
  subscriber: "Претплатник",
  waiting_list: "Листа на чекање",
  active: "Активен",
  inactive: "Неактивен",
  subscribers: "Претплатници",
  active_customers: "Активни купувачи",
  selected_contacts: "Избрани контакти",
  feed: "Храна",
  supplements: "Суплементи",
  bedding_hygiene: "Постелка и хигиена",
  packaging: "Пакување",
  transport: "Транспорт",
  labor_time: "Работа и време",
  utilities: "Режиски трошоци",
  maintenance: "Одржување",
  veterinary_medicine: "Ветеринарна грижа",
  equipment_tools: "Опрема и алати",
  land_facility: "Земјиште и објект",
  miscellaneous: "Разно",
  direct: "Директен",
  allocated: "Распределен",
  daily: "Дневно",
  monthly: "Месечно",
  manual: "Рачно",
  template: "Шаблон",
  reserved: "Резервирана",
  completed: "Завршена",
  cancelled: "Откажана",
  default: "Стандардна",
  manual_override: "Рачно зададена",
  draft: "Нацрт",
  sent: "Испратена",
  failed: "Неуспешна",
};

export function formatAdminValueLabel(value: string): string {
  return ADMIN_VALUE_LABELS[value] ?? value.replaceAll("_", " ");
}

export function formatAdminRecurringSchedule(template: {
  frequency: string;
  start_date: Date;
  end_date: Date | null;
}): string {
  const frequencyLabel = formatAdminValueLabel(template.frequency);
  const endDateLabel = template.end_date
    ? ` до ${formatDateOnly(template.end_date)}`
    : "";

  return `${frequencyLabel} од ${formatDateOnly(template.start_date)}${endDateLabel}`;
}

export function formatAdminActiveState(isActive: boolean): string {
  return isActive ? adminCopy.costs.active : adminCopy.costs.inactive;
}
